### ISSUE TITLE
Be more consistent about relationship name properties

### ISSUE THREAD

**Issue by Dhaulagiri** [elwayman02/ember-data-github#114]
There is a lack of consistency around whether a relationship property is prefixed with `github` or not.  In some cases we do and others we don't.

https://github.com/elwayman02/ember-data-github/blob/0989d8b2983be3c6d7bee400a6ac77ec3c52e254/addon/models/github-organization.js#L7

https://github.com/elwayman02/ember-data-github/blob/0989d8b2983be3c6d7bee400a6ac77ec3c52e254/addon/models/github-repository.js#L22

**Comment by elwayman02** [comment]
I would prefer not to prefix it in an object definition. Personally, I think it's only useful in the context of the broader file naming system, so that we don't conflict with the consuming app. Within the context of a "github organization", for example, we don't need to know that a "user" is a "github user". That's implied, imo.

**Comment by Dhaulagiri** [comment]
That makes sense to me. Less verbose seems preferable. This would be a breaking change, so I’m not sure the best way to handle. Bump minor version and highlight in the release notes how to adjust?? It should be a relatively minor inconvenience.

**Comment by elwayman02** [comment]
Breaking change is a major release, better to follow semver on this than to get a nice clean 1.0.0 release. Alternative is, if we are close to feature-complete on the API, maybe we can plan out a v1 release that is both feature complete *and* includes this breaking change? I'm not sure what we have left to fully support their API.

**Comment by Dhaulagiri** [comment]
Their api is pretty massive.  I think we are quite a ways away from supporting everything, but I haven't done a full accounting of everything.

**Comment by elwayman02** [comment]
Hmm, that's fair. Is there a core subset we can target for a v1 release, then? It seems unreasonable to hold back on calling this a fairly stable and usable addon if there is just a massive amount of work to do yet in order to support their full API.

(Perhaps this is a discussion for another issue)

**Comment by Dhaulagiri** [comment]
created a 1.0 milestone we can use to track what seems reasonable to do before cutting a v1 release.  I'll try to fill in some of the gaps once i have time.

**Comment by elwayman02** [comment]
Sounds good! I might be doing some more work on my website soon that will involve using this addon again, so if I'm in here making changes I might try to attack some of the milestone work as well.
